// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
  
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Kalle Jillheden")]
[assembly: AssemblyProduct("Robot++ CLI")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyVersion("0.1.18078.1845")]
[assembly: AssemblyFileVersion("0.1.18078.1845")]

[assembly: AssemblyTitle("Robot++ CLI")]
[assembly: AssemblyDescription("Command-line interface for the Robot++ language compiler.")]
[assembly: AssemblyCopyright("Copyright © 2018 Kalle Jillheden <https://github.com/jilleJr/RobotPlusPlus>")]

[assembly: NeutralResourcesLanguage("en")]

[assembly: ComVisible(false)]