// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
  
using System.Reflection;
using System.Resources;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Kalle Jillheden")]
[assembly: AssemblyProduct("Robot++ compiler")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyVersion("0.7.18211.2119")]
[assembly: AssemblyFileVersion("0.7.18211.2119")]

[assembly: AssemblyTitle("Robot++ Compiler")]
[assembly: AssemblyDescription("Compiler library for the Robot++ language.")]
[assembly: AssemblyCopyright("Copyright © 2018 Kalle Jillheden <https://github.com/jilleJr/RobotPlusPlus>")]

[assembly: NeutralResourcesLanguage("en")]

[assembly: ComVisible(false)]